Local:
  avatarPath: ./Folder/avatar
  publicPath: ./Folder/public
  userPath: ./Folder/user

pool:
  config:
    maxTotal: 10
    minIdle: 2
    maxIdle: 5
    testOnBorrow: true
    testOnReturn: true


spring:
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sparkies_cloud?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 821480